on:
  push:
    branches: [main, master, test, develop]
  pull_request:
    branches: [main, master, develop]

name: duckdb-test

jobs:
  Postgres-test:
    # if: github.repository == 'darwin-eu/CDMConnector'
    runs-on: ubuntu-latest
    container:
      image: executionengine.azurecr.io/darwin-base:v0.3
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        TESTTHAT_CPUS : 1

    name: duckdb-test

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2

      - name: Install packages
        run: |
          print(getwd())
          print(list.files())
          install.packages("devtools", repos = "https://cloud.r-project.org/")
          install.packages("omopgenerics", repos = "https://cloud.r-project.org/")
          install.packages("palmerpenguins", repos = "https://cloud.r-project.org/")
          install.packages("duckdb", repos = "https://cloud.r-project.org/")

        shell: Rscript {0}

      - name: Run tests on duckdb
        run: R -e 'devtools::install(); withr::with_envvar(new = c("CI_TEST_DB" = "duckdb", "TEST_USING_DATABASE_CONNECTOR" = "FALSE"), testthat::test_local())'


